первый набросок разметки
htmlacademy-htmlcss/1567151-sedona-29 pull request #2
Opened 2020-09-16 17:30 UTC by bykovmikhail

первый набросок разметки

2020-09-17 11:33 UTC, DoberBober commented on img/index.html
> +<!DOCTYPE html>
Лишний файл какой-то.

2020-09-17 11:33 UTC, DoberBober commented on index.html
> +    	<p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS, уровень 1</a>».</p>
Эту строку-заглушку удали. В макете ж нет его.

2020-09-17 11:34 UTC, DoberBober commented on index.html
> +    			<ul>
Перед ul вставь ещё ссылку с логотипом.

2020-09-17 11:35 UTC, DoberBober commented on index.html
> +    		<h2>WELKOM</h1>
В этом section будет только одна картинка (со всеми этими текстами) и всё. А горы уже будут фоном в CSS.

2020-09-17 11:36 UTC, DoberBober commented on index.html
> +    			<h1>СЕДОНА - НЕБОЛЬШОЙ ГОРОДОК В АРИЗОНЕ,<br>ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО</h1>
br-ки везде удали. Переносы текста можно сделать и через CSS. Если не будет получаться, тогда уже расставишь.
+напиши текст не капсом, а нормально. Капс тоже желательно в CSS делать, чтобы, в случае чего, можно было спокойно отключить, не набирая заново текст.

2020-09-17 11:36 UTC, DoberBober commented on index.html
> +    			<h3>рассмотрим 5 причин, по которым седона лучше, чем гранд каньон</h3>
p или strong, скорее.

2020-09-17 11:41 UTC, DoberBober commented on index.html
> +    			<ul>
Попробуй такую структуру:
![image](https://user-images.githubusercontent.com/18398812/93465453-7e6c7580-f8f3-11ea-89cc-a5c7667a3bf7.png)
Списком ты можешь сделать (если хочешь):
- Нижний красный блок (по аналогии будет и нижний блок "небольшая площадь/красивая дорога/мало туристов").
- Зелёный блок (будет всего 4 пункта в списке, два красных на скрине, два внизу).

2020-09-17 11:43 UTC, DoberBober commented on index.html
> +    			</ul>
Тут лишние закрывающие теги и не хватает нижней части сайта.

2020-09-17 11:43 UTC, DoberBober requested changes
-

2020-09-22 18:36 UTC, DoberBober commented on catalog.html
> +  		<img src="logo.jpg" width="" height="" alt="логотип">
Логотип по клику будет вести на главную страницу. Поэтому оберни её в `a` и пропиши `href="index.html`.

2020-09-22 18:38 UTC, DoberBober commented on catalog.html
> +  		<p>инфраструктура</p>
Тут как обсуждали: три колонки.
Ещё один момент: в будущем тебе будет проще, если ты инпуты поставишь перед лейблами (при этом надо будет привязать их друг к другу через for/id):
```
<input type="checkbox" id="checkbox1">
<label for="checkbox1">бассейн</label>
```

2020-09-22 18:38 UTC, DoberBober commented on catalog.html
> +  </main>
Сами гостиницы вывести.

2020-09-22 18:39 UTC, DoberBober commented on catalog.html
> +  		<nav>
nav тут можно удалить. Содержимое надо будет разбить на три колонки.

2020-09-22 18:39 UTC, DoberBober commented on index.html
> +    			<ul>
Тут забыл в ссылку обернуть логотип.

2020-09-22 18:42 UTC, DoberBober commented on index.html
> +    			<ul>
Разбивку поправь. Опять же, идёшь от крупного к мелкому. Чтобы было проще, делишь блок на строки (всего их четыре, но на скрине два только, их и будем рассматривать). Первая строка делится на две части - слева блок с текстом, справа картинка. Левая часть делится на три: заголовок, номер, текст. Списком это назвать нельзя, поэтому левая часть - это не ul/li, а просто див.

Вторую строку списком уже назвать можно (три пункта в нём и они все равнозначные). Значит синие элементы - это li-шки, а сама строка - ul. В каждой лишке три элемента: картинка, заголовок, текст.

2020-09-22 18:44 UTC, DoberBober commented on index.html
> +    			<h1>заинтересовались?</h1>
h1 - это главный заголовок на странице. Он должен быть один и должен при этом описывать всю страницу. Поэтому тут, скорее, h2 (как подзаголовок).

2020-09-22 18:44 UTC, DoberBober commented on index.html
> +    			<h1>поиск гостиниц в седоне</h1>
Это ссылка.

2020-09-22 18:44 UTC, DoberBober commented on index.html
> +    		<p>visit sedona тел:+7(495) 666-01-66</p>
Тут аналогично футеру на второй странице. Разбить на три части.

2020-09-22 18:45 UTC, DoberBober commented on index.html
> +    		</nav>
Лишний тег.

2020-09-22 18:45 UTC, DoberBober requested changes
Есть ещё доработки. Пару пунктов пропустил, +я добавил замечания по второй странице.

2020-09-23 17:07 UTC, bykovmikhail commented
исправил замечания. разметил вторую страницу.

2020-09-23 17:41 UTC, DoberBober commented on catalog.html
> +  				<form action="#" method="get">
Тут form не нужен, потому что целиком весь фильтр потом будет обёрнут в form.

2020-09-23 17:41 UTC, DoberBober commented on catalog.html
> +  					<input type="button" value="показать">
type="submit".

2020-09-23 17:42 UTC, DoberBober commented on catalog.html
> +  				<a href="blank.html"></a>
Пустую ссылку удали.

2020-09-23 17:42 UTC, DoberBober commented on catalog.html
> +  				<a href="blank.html">по рейтингу</a>
Добавь ещё две ссылки (треугольники).

2020-09-23 17:42 UTC, DoberBober commented on catalog.html
> +  				<input type="button" value="подробнее">
Подробнее и забронировать - ссылки.

2020-09-23 17:42 UTC, DoberBober commented on index.html
> +    			<img src="logo.jpg" width="138" height="70" alt="логотип">
На главной забыл логотип в ссылку обернуть.

2020-09-23 17:42 UTC, DoberBober commented on index.html
> +    			<h2>поиск гостиниц в седоне</h2>
Поиск гостиницы - это ссылка.

2020-09-23 17:43 UTC, DoberBober reviewed
Само задание приму. У тебя в разделе разметки есть ещё второе задание. Правки, которые написал поправь и скинь уже второе. (В этот раз надо будет пулреквест тоже создать, так как это задание я принимаю.)

2020-09-23 17:43 UTC, merged

2020-09-23 17:49 UTC, DoberBober commented on index.html
> +    			<ul>
Структуру тут не поправил. Див, в котором лежат два дива и два ul.
![image](https://user-images.githubusercontent.com/18398812/94049906-3b703d80-fdde-11ea-879d-ce06a364002f.png)